name: Deploy

permissions:
  actions: read
  contents: read
  checks: read
  packages: write
  statuses: write

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  push_to_github_packages:
    name: Push to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set RELEASE_TAG
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set GitHub Packages Publish API Key
        run: |
          set +x
          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :github: Bearer ${{ secrets.GITHUB_TOKEN }}
          EOF

          chmod 0600 ~/.gem/credentials
          set -x
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Set GitHub Packages Read API Key
        run: |
          bundle config https://rubygems.pkg.github.com/packfiles ${{ secrets.GH_PACKAGES_SVC_ACCOUNT_USERNAME }}:${{ secrets.GH_PACKAGES_SVC_ACCOUNT_RO_PAT }}
      - name: Install Dependendies
        run: bundle install
      - name: Check Capybara::Playwright::VERSION
        run: bundle exec ruby -e 'raise "invalid Capybara::Playwright::VERSION" unless Capybara::Playwright::VERSION == ENV["RELEASE_TAG"]'
      - run: rake build
      - run: gem push pkg/capybara-playwright-driver-$RELEASE_TAG.gem --key github --host "https://rubygems.pkg.github.com/packfiles"
